### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Fishersponge** [DUTANGx/Chinese-BERT-as-language-model#1]
无法加载预训练的bert模型，model_path应当防止哪个文件的地址？

**Comment by DUTANGx** [comment]
Hello sry for late reply. MODEL_PATH已经独立出来作为初始化的参数。代码使用的huggingface的transformer，可以参考https://github.com/ymcui/Chinese-BERT-wwm#%E5%BF%AB%E9%80%9F%E5%8A%A0%E8%BD%BD 的初始化例子。

**Comment by DUTANGx** [comment]
> 无法加载预训练的bert模型，model_path应当防止哪个文件的地址？

Hi Fishersponge
Sry for late reply. MODEL_PATH已经独立出来作为初始化的参数。
代码使用的huggingface的transformer，可以参考https://github.com/ymcui/Chinese-BERT-wwm#%E5%BF%AB%E9%80%9F%E5%8A%A0%E8%BD%BD 的初始化例子。
